[package]
name = "cdragon-rman"
version = "0.1.0"
authors = ["BenoÃ®t Ryder <benoit@ryder.fr>"]
edition = "2021"

[dependencies]
cdragon-utils = { path = "../cdragon-utils", features = ["parsing"] }
nom = "7"
thiserror = "1"
zstd = "0.12"

