[package]
name = "cdragon-prop"
version = "0.1.0"
authors = ["Beno√Æt Ryder <benoit@ryder.fr>"]
edition = "2018"

[dependencies]
cdragon-utils = { path = "../cdragon-utils" }
cdragon-wad = { path = "../cdragon-wad" }
nom = "5"
derive-try-from-primitive = "0.1"
walkdir = "2"

[features]
wasm = ["cdragon-wad/wasm"]

